In [1]:
import sqlite3
import pandas as pd

# bronnen
conn_av = sqlite3.connect("BikeToDrive_1_Accessoireverkoop.db")
conn_fv = sqlite3.connect("BikeToDrive_2_Fietsverkoop.db")
conn_oh = sqlite3.connect("BikeToDrive_3_Onderhoud.db")
conn_ai = sqlite3.connect("BikeToDrive_4_Accessoire_Inkoop.db")
conn_fi = sqlite3.connect("BikeToDrive_5_Fiets_Inkoop.db")

# SDM (doel)
conn_sdm = sqlite3.connect("SDM1.db")

print("connecties gelukt")

connecties gelukt

In [3]:
pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn_av)

                 name
0  Accessoire_Verkoop
1             Monteur
2         Leverancier
3          Accessoire
4             Filiaal
5               Klant

In [4]:
df_av = pd.read_sql("SELECT * FROM Klant", conn_av)
df_av.head()

   klantnr            naam           adres woonplaats geslacht geboortedatum
0        1      Jan Jansen   Kerkstraat 12  Amsterdam        M    1985-03-22
1        2  Sophie de Boer     Lindelaan 8  Rotterdam        V    1990-07-11
2        3   Pieter Visser   Havenstraat 3   Den Haag        M    1978-11-05
3        4       Emma Smit    Boomgaard 22    Haarlem        V    1995-02-18
4        5      Tom Bakker  Stationsweg 44     Leiden        M    1982-09-09

In [5]:
print("Accessoireverkoop:")
print(pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn_av))

print("\nFietsverkoop:")
print(pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn_fv))

print("\nOnderhoud:")
print(pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn_oh))

print("\nAccessoire Inkoop:")
print(pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn_ai))

print("\nFiets Inkoop:")
print(pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn_fi))

Accessoireverkoop:
                 name
0  Accessoire_Verkoop
1             Monteur
2         Leverancier
3          Accessoire
4             Filiaal
5               Klant

Fietsverkoop:
            name
0  Fiets_Verkoop
1          Fiets
2        Monteur
3      Fabrikant
4        Filiaal
5          Klant

Onderhoud:
        name
0  Onderhoud
1      Fiets
2    Monteur
3  Fabrikant
4    Filiaal

Accessoire Inkoop:
                name
0  Accessoire_Inkoop
1         Accessoire
2        Leverancier

Fiets Inkoop:
           name
0  Fiets_Inkoop
1         Fiets
2     Fabrikant

In [6]:
df_klant = pd.read_sql("SELECT * FROM Klant", conn_av)
df_klant.head()

   klantnr            naam           adres woonplaats geslacht geboortedatum
0        1      Jan Jansen   Kerkstraat 12  Amsterdam        M    1985-03-22
1        2  Sophie de Boer     Lindelaan 8  Rotterdam        V    1990-07-11
2        3   Pieter Visser   Havenstraat 3   Den Haag        M    1978-11-05
3        4       Emma Smit    Boomgaard 22    Haarlem        V    1995-02-18
4        5      Tom Bakker  Stationsweg 44     Leiden        M    1982-09-09

In [7]:
df_klant.to_sql("Klant", conn_sdm, if_exists="append", index=False)

20

In [8]:
pd.read_sql("SELECT * FROM Klant", conn_sdm)

,klantnr,naam,adres,woonplaats,geslacht,geboortedatum
0,1,Jan Jansen,Kerkstraat 12,Amsterdam,M,1985-03-22
1,2,Sophie de Boer,Lindelaan 8,Rotterdam,V,1990-07-11
2,3,Pieter Visser,Havenstraat 3,Den Haag,M,1978-11-05
3,4,Emma Smit,Boomgaard 22,Haarlem,V,1995-02-18
4,5,Tom Bakker,Stationsweg 44,Leiden,M,1982-09-09
5,6,Lisa Meijer,Dijkstraat 10,Zaandam,V,1993-12-30
6,7,Bart de Vries,Brouwersgracht 7,Delft,M,1976-06-06
7,8,Julia van Dijk,Plataanlaan 5,Hoorn,V,2000-01-15
8,9,Kevin Mol,Singel 99,Alkmaar,M,1989-08-01
9,10,Nina Groen,Waterstraat 16,Schiedam,V,1991-05-25
10,11,Daan Willems,Parklaan 31,Haarlem,M,1987-10-12
11,12,Eva Vos,Zomerweg 2,Zoetermeer,V,1996-04-03
12,13,Rik de Jong,Noorderstraat 88,Hilversum,M,1980-12-21
13,14,Mila Kuipers,Heemraadssingel 15,Rotterdam,V,1998-09-17
14,15,Sam Reinders,Beethovenlaan 13,Haarlem,M,1983-01-29
15,16,Fleur Schouten,Tulpenstraat 5,Amsterdam,V,1994-06-08
16,17,Lars van den Berg,Kade 101,Leiden,M,1988-03-02
17,18,Tess van Leeuwen,Markt 22,Dordrecht,V,1997-07-19
18,19,Jesse van Dam,Zuidlaan 7,Alphen aan den Rijn,M,1981-11-27
19,20,Noa Blom,Vondelstraat 18,Zaandam,V,2002-02-10

In [9]:
df_filiaal = pd.read_sql("SELECT * FROM Filiaal", conn_av)
df_filiaal.head()

   filiaalnr                    naam              adres      provincie
0          1     BikeWorld Amsterdam  Prinsengracht 100  Noord-Holland
1          2     FietsGigant Haarlem     Grote Markt 22  Noord-Holland
2          3  FietsExpress Rotterdam      Coolsingel 55   Zuid-Holland
3          4        CycleCity Leiden      Breestraat 48   Zuid-Holland

In [10]:
df_filiaal.to_sql("Filiaal", conn_sdm, if_exists="append", index=False)

4

In [11]:
pd.read_sql("SELECT * FROM Filiaal", conn_sdm)

   filiaalnr                    naam              adres      provincie
0          1     BikeWorld Amsterdam  Prinsengracht 100  Noord-Holland
1          2     FietsGigant Haarlem     Grote Markt 22  Noord-Holland
2          3  FietsExpress Rotterdam      Coolsingel 55   Zuid-Holland
3          4        CycleCity Leiden      Breestraat 48   Zuid-Holland

In [12]:
df_monteur = pd.read_sql("SELECT * FROM Monteur", conn_av)
df_monteur.head()

   monteurnr            naam  woonplaats  uurloon  filiaal
0          1    Tom van Dijk   Amsterdam    19.50        1
1          2  Lisa Verhoeven  Amstelveen    18.75        1
2          3   Kevin Jaspers     Zaandam    20.00        1
3          4    Romy Willems     Haarlem    17.80        2
4          5   Daan de Groot   Rotterdam    21.00        3

In [13]:
df_monteur.to_sql("Monteur", conn_sdm, if_exists="append", index=False)

10

In [14]:
pd.read_sql("SELECT * FROM Monteur", conn_sdm)

   monteurnr             naam  woonplaats  uurloon  filiaal
0          1     Tom van Dijk   Amsterdam    19.50        1
1          2   Lisa Verhoeven  Amstelveen    18.75        1
2          3    Kevin Jaspers     Zaandam    20.00        1
3          4     Romy Willems     Haarlem    17.80        2
4          5    Daan de Groot   Rotterdam    21.00        3
5          6  Sophie de Leeuw    Schiedam    19.90        3
6          7   Mark van Vliet   Dordrecht    20.25        3
7          8     Jesse Peters      Leiden    16.95        4
8          9       Eva Meijer  Zoetermeer    18.40        4
9         10   Milan de Bruin     Zaandam    17.25        2

In [15]:
df_leverancier = pd.read_sql("SELECT * FROM Leverancier", conn_av)
df_leverancier.head()

   leveranciernr               naam             adres woonplaats
0              1       BikeParts BV  Fietsenstraat 12  Amsterdam
1              2      CycleSupplies   Rembrandtlaan 7  Rotterdam
2              3  TwoWheels Trading      Marktplein 5   Den Haag
3              4   DutchBike Import           Kade 22     Leiden
4              5       UrbanGear NL    Stationsweg 15    Utrecht

In [16]:
df_leverancier.to_sql("Leverancier", conn_sdm, if_exists="append", index=False)

5

In [17]:
pd.read_sql("SELECT * FROM Leverancier", conn_sdm)

   leveranciernr               naam             adres woonplaats
0              1       BikeParts BV  Fietsenstraat 12  Amsterdam
1              2      CycleSupplies   Rembrandtlaan 7  Rotterdam
2              3  TwoWheels Trading      Marktplein 5   Den Haag
3              4   DutchBike Import           Kade 22     Leiden
4              5       UrbanGear NL    Stationsweg 15    Utrecht

In [18]:
df_accessoire = pd.read_sql("SELECT * FROM Accessoire", conn_av)
df_accessoire.head()

,accessoirenr,naam,standaardprijs,inkoopprijs,soort,leverancier
0,1,LED voorlamp,14.99,8.50,Verlichting,1
1,2,LED achterlicht,12.99,7.25,Verlichting,1
2,3,USB-oplaadbare fietslamp,24.95,15.00,Verlichting,1
3,4,Ringslot AXA,19.95,11.40,Sloten,1
4,5,Ketting met cijferslot,17.50,10.00,Sloten,2

In [19]:
df_accessoire.to_sql("Accessoire", conn_sdm, if_exists="append", index=False)

10

In [20]:
pd.read_sql("SELECT * FROM Accessoire", conn_sdm)

,accessoirenr,naam,standaardprijs,inkoopprijs,soort,leverancier
0,1,LED voorlamp,14.99,8.50,Verlichting,1
1,2,LED achterlicht,12.99,7.25,Verlichting,1
2,3,USB-oplaadbare fietslamp,24.95,15.00,Verlichting,1
3,4,Ringslot AXA,19.95,11.40,Sloten,1
4,5,Ketting met cijferslot,17.50,10.00,Sloten,2
5,6,U-slot met beugel,29.99,18.75,Sloten,2
6,7,Dubbele fietstas zwart,39.95,24.90,Tassen,2
7,8,Enkele schouderfietstas,27.50,16.80,Tassen,3
8,9,Waterdichte zadeltas,14.25,8.95,Tassen,3
9,10,Kinderfietsmand roze,11.99,6.60,Tassen,4

In [21]:
df_av_verkoop = pd.read_sql("SELECT * FROM Accessoire_Verkoop", conn_av)
df_av_verkoop.head()

,accessoire_verkoopnr,datum,aantal,verkoopprijs,klant,accessoire,monteur
0,1,2024-01-23,3,13.90,9,1,5
1,2,2024-10-03,2,11.27,7,1,7
2,3,2024-10-30,2,37.21,5,7,7
3,4,2024-11-16,1,10.71,9,10,2
4,5,2024-01-02,4,15.20,20,1,9

In [22]:
df_av_verkoop.to_sql("Accessoire_Verkoop", conn_sdm, if_exists="append", index=False)

100

In [23]:
pd.read_sql("SELECT * FROM Accessoire_Verkoop", conn_sdm)

,accessoire_verkoopnr,datum,aantal,verkoopprijs,klant,accessoire,monteur
0,1,2024-01-23,3,13.90,9,1,5
1,2,2024-10-03,2,11.27,7,1,7
2,3,2024-10-30,2,37.21,5,7,7
3,4,2024-11-16,1,10.71,9,10,2
4,5,2024-01-02,4,15.20,20,1,9
...,...,...,...,...,...,...,...
95,96,2024-01-10,3,15.56,12,5,5
96,97,2024-08-25,4,32.73,1,6,8
97,98,2024-09-29,2,12.62,3,1,4
98,99,2024-04-12,3,18.90,1,5,3
99,100,2024-10-27,4,12.67,18,5,10

In [24]:
df_fiets = pd.read_sql("SELECT * FROM Fiets", conn_fv)
df_fiets.head()

,fietsnr,soort,merk,type,standaardprijs,inkoopprijs,kleur,fabrikant
0,1,Stadsfiets,SpeedCycle,STA-240,962.33,815.25,Groen,1
1,2,Mountainbike,SpeedCycle,MOU-394,890.64,733.06,Zwart,1
2,3,Mountainbike,SpeedCycle,MOU-341,547.79,472.47,Geel,1
3,4,Racefiets,SpeedCycle,RAC-241,991.75,787.67,Groen,1
4,5,Mountainbike,SpeedCycle,MOU-566,879.44,778.29,Geel,1

In [25]:
df_fiets.to_sql("Fiets", conn_sdm, if_exists="append", index=False)

75

In [26]:
pd.read_sql("SELECT * FROM Fiets", conn_sdm)

,fietsnr,soort,merk,type,standaardprijs,inkoopprijs,kleur,fabrikant
0,1,Stadsfiets,SpeedCycle,STA-240,962.33,815.25,Groen,1
1,2,Mountainbike,SpeedCycle,MOU-394,890.64,733.06,Zwart,1
2,3,Mountainbike,SpeedCycle,MOU-341,547.79,472.47,Geel,1
3,4,Racefiets,SpeedCycle,RAC-241,991.75,787.67,Groen,1
4,5,Mountainbike,SpeedCycle,MOU-566,879.44,778.29,Geel,1
...,...,...,...,...,...,...,...,...
70,71,Elektrische fiets,FastFrame,ELE-120,731.83,576.62,Grijs,9
71,72,Racefiets,FastFrame,RAC-797,399.31,327.02,Rood,9
72,73,Stadsfiets,OranjeFiets,STA-974,731.99,622.99,Geel,10
73,74,Racefiets,OranjeFiets,RAC-701,589.50,513.51,Geel,10
74,75,Elektrische fiets,OranjeFiets,ELE-507,997.58,772.38,Wit,10

In [27]:
df_fabrikant = pd.read_sql("SELECT * FROM Fabrikant", conn_fv)
df_fabrikant.head()

   fabrikantnr           naam             adres     plaats
0            1  SpeedCycle BV    Spoorstraat 12  Eindhoven
1            2  UrbanBike Co.  Keizersgracht 45  Amsterdam
2            3   HollandRider     Marktstraat 9    Utrecht
3            4    EcoWheelers           Kade 33      Delft
4            5    DutchMotion       Westplein 7  Rotterdam

In [28]:
df_fabrikant.to_sql("Fabrikant", conn_sdm, if_exists="append", index=False)

10

In [29]:
pd.read_sql("SELECT * FROM Fabrikant", conn_sdm)

   fabrikantnr           naam             adres      plaats
0            1  SpeedCycle BV    Spoorstraat 12   Eindhoven
1            2  UrbanBike Co.  Keizersgracht 45   Amsterdam
2            3   HollandRider     Marktstraat 9     Utrecht
3            4    EcoWheelers           Kade 33       Delft
4            5    DutchMotion       Westplein 7   Rotterdam
5            6     NordicBike   Prinsestraat 18   Groningen
6            7      CycleTech        Boslaan 60    Den Haag
7            8      GreenGear    Leliestraat 24    Nijmegen
8            9      FastFrame      Rivierlaan 3  Maastricht
9           10    OranjeFiets          Brink 88      Zwolle

In [30]:
df_fv_verkoop = pd.read_sql("SELECT * FROM Fiets_Verkoop", conn_fv)
df_fv_verkoop.head()

   fiets_verkoopnr       datum  aantal  verkoopprijs  klant  fiets  monteur
0                1  2024-03-09       3       1020.48     25     61        6
1                2  2024-07-12       1       1391.84     23     58        5
2                3  2024-11-21       2       1891.33      2     45       10
3                4  2024-05-26       3        995.53      9     29        5
4                5  2024-04-15       2       1568.90     13     38       10

In [31]:
df_fv_verkoop.to_sql("Fiets_Verkoop", conn_sdm, if_exists="append", index=False)

150

In [32]:
pd.read_sql("SELECT * FROM Fiets_Verkoop", conn_sdm)

     fiets_verkoopnr       datum  aantal  verkoopprijs  klant  fiets  monteur
0                  1  2024-03-09       3       1020.48     25     61        6
1                  2  2024-07-12       1       1391.84     23     58        5
2                  3  2024-11-21       2       1891.33      2     45       10
3                  4  2024-05-26       3        995.53      9     29        5
4                  5  2024-04-15       2       1568.90     13     38       10
..               ...         ...     ...           ...    ...    ...      ...
145              146  2024-07-02       1        902.77     14     10        4
146              147  2024-02-14       3       1159.80      6      1        8
147              148  2024-09-16       3       1075.78     19     68        7
148              149  2024-04-27       3       1581.13      9     38        3
149              150  2024-11-21       2        911.00      8     47        2

[150 rows x 7 columns]

In [33]:
df_onderhoud = pd.read_sql("SELECT * FROM Onderhoud", conn_oh)
df_onderhoud.head()

   onderhoudnr       datum         starttijd          eindtijd  fiets  monteur
0            1  2024-12-28  15:00:00.0000000  16:00:00.0000000     22       14
1            2  2024-02-05  14:00:00.0000000  15:00:00.0000000     18        8
2            3  2024-08-01  10:00:00.0000000  11:00:00.0000000      3       14
3            4  2024-11-16  10:00:00.0000000  11:00:00.0000000     11        2
4            5  2024-08-01  11:00:00.0000000  12:00:00.0000000     60       15

In [34]:
df_onderhoud.to_sql("Onderhoud", conn_sdm, if_exists="append", index=False)

50

In [35]:
pd.read_sql("SELECT * FROM Onderhoud", conn_sdm)

,onderhoudnr,datum,starttijd,eindtijd,fiets,monteur
0,1,2024-12-28,15:00:00.0000000,16:00:00.0000000,22,14
1,2,2024-02-05,14:00:00.0000000,15:00:00.0000000,18,8
2,3,2024-08-01,10:00:00.0000000,11:00:00.0000000,3,14
3,4,2024-11-16,10:00:00.0000000,11:00:00.0000000,11,2
4,5,2024-08-01,11:00:00.0000000,12:00:00.0000000,60,15
5,6,2024-12-08,13:00:00.0000000,14:00:00.0000000,18,13
6,7,2024-05-14,11:00:00.0000000,12:00:00.0000000,4,8
7,8,2024-10-10,09:00:00.0000000,10:00:00.0000000,67,3
8,9,2024-06-29,08:00:00.0000000,09:00:00.0000000,18,12
9,10,2024-08-21,08:00:00.0000000,09:00:00.0000000,33,2
10,11,2024-08-20,08:00:00.0000000,09:00:00.0000000,66,8
11,12,2024-09-15,11:00:00.0000000,12:00:00.0000000,59,6
12,13,2024-05-27,08:00:00.0000000,09:00:00.0000000,30,9
13,14,2024-07-21,10:00:00.0000000,11:00:00.0000000,68,5
14,15,2024-02-03,12:00:00.0000000,13:00:00.0000000,20,15
15,16,2024-09-27,15:00:00.0000000,16:00:00.0000000,57,5
16,17,2024-12-21,12:00:00.0000000,13:00:00.0000000,64,9
17,18,2024-01-08,10:00:00.0000000,11:00:00.0000000,22,1
18,19,2024-11-12,12:00:00.0000000,13:00:00.0000000,29,9
19,20,2024-12-27,08:00:00.0000000,09:00:00.0000000,59,10
20,21,2024-09-30,12:00:00.0000000,13:00:00.0000000,21,4
21,22,2024-05-07,11:00:00.0000000,12:00:00.0000000,29,7
22,23,2024-08-13,08:00:00.0000000,09:00:00.0000000,26,13
23,24,2024-07-27,11:00:00.0000000,12:00:00.0000000,59,8
24,25,2024-08-29,14:00:00.0000000,15:00:00.0000000,26,7
25,26,2024-12-14,08:00:00.0000000,09:00:00.0000000,64,8
26,27,2024-02-06,09:00:00.0000000,10:00:00.0000000,3,5
27,28,2024-11-15,11:00:00.0000000,12:00:00.0000000,29,10
28,29,2024-05-19,11:00:00.0000000,12:00:00.0000000,56,12
29,30,2024-07-26,11:00:00.0000000,12:00:00.0000000,11,5
30,31,2024-02-23,13:00:00.0000000,14:00:00.0000000,22,12
31,32,2024-10-17,10:00:00.0000000,11:00:00.0000000,26,10
32,33,2024-11-01,15:00:00.0000000,16:00:00.0000000,56,8
33,34,2024-10-04,15:00:00.0000000,16:00:00.0000000,20,5
34,35,2024-07-05,11:00:00.0000000,12:00:00.0000000,11,14
35,36,2024-01-28,09:00:00.0000000,10:00:00.0000000,18,12
36,37,2024-09-01,11:00:00.0000000,12:00:00.0000000,26,14
37,38,2024-09-23,09:00:00.0000000,10:00:00.0000000,32,5
38,39,2024-11-08,13:00:00.0000000,14:00:00.0000000,33,12
39,40,2024-12-31,14:00:00.0000000,15:00:00.0000000,68,3
40,41,2024-12-13,15:00:00.0000000,16:00:00.0000000,49,15
41,42,2024-02-23,15:00:00.0000000,16:00:00.0000000,19,2
42,43,2024-12-13,15:00:00.0000000,16:00:00.0000000,61,10
43,44,2024-05-03,13:00:00.0000000,14:00:00.0000000,29,8
44,45,2024-08-10,08:00:00.0000000,09:00:00.0000000,67,4
45,46,2024-08-28,13:00:00.0000000,14:00:00.0000000,69,12
46,47,2024-12-11,14:00:00.0000000,15:00:00.0000000,4,6
47,48,2024-03-04,09:00:00.0000000,10:00:00.0000000,59,11
48,49,2024-07-03,12:00:00.0000000,13:00:00.0000000,21,6
49,50,2024-07-08,12:00:00.0000000,13:00:00.0000000,67,15

In [36]:
df_ai = pd.read_sql("SELECT * FROM Accessoire_Inkoop", conn_ai)
df_ai.head()

   inkoopnr  inkoopmaand  inkoopjaar  aantal  accessoire
0         1            4        2024      38           7
1         2            8        2024      31           6
2         3            1        2024      41           2
3         4            1        2024      21           1
4         5           10        2024      31           4

In [37]:
df_ai.to_sql("Accessoire_Inkoop", conn_sdm, if_exists="append", index=False)

50

In [38]:
pd.read_sql("SELECT * FROM Accessoire_Inkoop", conn_sdm)

    inkoopnr  inkoopmaand  inkoopjaar  aantal  accessoire
0          1            4        2024      38           7
1          2            8        2024      31           6
2          3            1        2024      41           2
3          4            1        2024      21           1
4          5           10        2024      31           4
5          6            9        2024      27           6
6          7            6        2024      38           2
7          8            1        2024      27           7
8          9           11        2024      49          11
9         10            8        2024      47           4
10        11            7        2024      16          13
11        12            9        2024      30           2
12        13            7        2024      18           2
13        14            6        2024      25          10
14        15            2        2024      34           1
15        16            5        2024      42          13
16        17            9        2024      17           1
17        18            1        2024      40           2
18        19            9        2024      21           8
19        20            3        2024       9           8
20        21            3        2024      33           2
21        22            5        2024      50          11
22        23           10        2024      45           3
23        24           12        2024      25          11
24        25            3        2024      10          13
25        26            7        2024      18          13
26        27            3        2024      47           7
27        28            8        2024      29           5
28        29           10        2024      26           7
29        30            1        2024      36           4
30        31           10        2024       5           7
31        32           11        2024      39          12
32        33            4        2024      40           3
33        34            2        2024      50           4
34        35            4        2024      31           4
35        36           11        2024      27          11
36        37            8        2024       9           9
37        38            3        2024      14          12
38        39            3        2024      33          12
39        40            5        2024      36           2
40        41            3        2024      18           8
41        42            3        2024      28           4
42        43            4        2024      42           9
43        44            3        2024      34          12
44        45            2        2024      37          11
45        46            6        2024      35           6
46        47            8        2024      38          10
47        48            4        2024      33           9
48        49            6        2024      34           3
49        50            7        2024      25          10

In [39]:
df_fi = pd.read_sql("SELECT * FROM Fiets_Inkoop", conn_fi)
df_fi.head()

   inkoopnr  inkoopmaand  inkoopjaar  aantal  fiets
0         1            4        2024       3     60
1         2           10        2024       6      6
2         3           12        2024       2      8
3         4           10        2024       2      3
4         5            8        2024       3     44

In [40]:
df_fi.to_sql("Fiets_Inkoop", conn_sdm, if_exists="append", index=False)

100

In [41]:
pd.read_sql("SELECT * FROM Fiets_Inkoop", conn_sdm)

    inkoopnr  inkoopmaand  inkoopjaar  aantal  fiets
0          1            4        2024       3     60
1          2           10        2024       6      6
2          3           12        2024       2      8
3          4           10        2024       2      3
4          5            8        2024       3     44
..       ...          ...         ...     ...    ...
95        96            4        2024       7     56
96        97           12        2024       5     43
97        98           11        2024       2     18
98        99            7        2024       1     18
99       100           12        2024       5     26

[100 rows x 5 columns]

Reset voor huidige SDM

In [61]:
conn_sdm.execute("DELETE FROM Accessoire_Verkoop")
conn_sdm.execute("DELETE FROM Fiets_Verkoop")
conn_sdm.execute("DELETE FROM Onderhoud")
conn_sdm.execute("DELETE FROM Accessoire_Inkoop")
conn_sdm.execute("DELETE FROM Fiets_Inkoop")

conn_sdm.execute("DELETE FROM Klant")
conn_sdm.execute("DELETE FROM Monteur")
conn_sdm.execute("DELETE FROM Filiaal")
conn_sdm.execute("DELETE FROM Leverancier")
conn_sdm.execute("DELETE FROM Fabrikant")
conn_sdm.execute("DELETE FROM Accessoire")
conn_sdm.execute("DELETE FROM Fiets")

conn_sdm.commit()

print("SDM reset gelukt")

SDM reset gelukt

klant uit AV

In [83]:
try:
    print("Start laden Klant")

    df = pd.read_sql("SELECT * FROM Klant", conn_av)
    print("Klant opgehaald uit bron | aantal rijen:", len(df))

    df.to_sql("Klant", conn_sdm, if_exists="append", index=False)
    print("Klant geladen in SDM")

except Exception as e:
    print("FOUT bij laden van Klant:", e)

Start laden Klant
Klant opgehaald uit bron | aantal rijen: 21
FOUT bij laden van Klant: UNIQUE constraint failed: Klant.klantnr

Monteur uit AV

In [84]:
try:
    print("Start laden Monteur")

    df = pd.read_sql("SELECT * FROM Monteur", conn_av)
    print("Monteur opgehaald | rijen:", len(df))

    df.to_sql("Monteur", conn_sdm, if_exists="append", index=False)
    conn_sdm.commit()

    print("Monteur succesvol geladen\n")

except Exception as e:
    print("FOUT bij Monteur:", e, "\n")

Start laden Monteur
Monteur opgehaald | rijen: 10
FOUT bij Monteur: UNIQUE constraint failed: Monteur.monteurnr

Filiaal uit AV

In [85]:
try:
    print("Start laden Filiaal")

    df = pd.read_sql("SELECT * FROM Filiaal", conn_av)
    print("Filiaal opgehaald | rijen:", len(df))

    df.to_sql("Filiaal", conn_sdm, if_exists="append", index=False)
    conn_sdm.commit()

    print("Filiaal succesvol geladen\n")

except Exception as e:
    print("FOUT bij Filiaal:", e, "\n")

Start laden Filiaal
Filiaal opgehaald | rijen: 4
FOUT bij Filiaal: UNIQUE constraint failed: Filiaal.filiaalnr

Leverancier uit AV

In [86]:
try:
    print("Start laden Leverancier")

    df = pd.read_sql("SELECT * FROM Leverancier", conn_av)
    print("Leverancier opgehaald | rijen:", len(df))

    df.to_sql("Leverancier", conn_sdm, if_exists="append", index=False)
    conn_sdm.commit()

    print("Leverancier succesvol geladen\n")

except Exception as e:
    print("FOUT bij Leverancier:", e, "\n")

Start laden Leverancier
Leverancier opgehaald | rijen: 5
FOUT bij Leverancier: UNIQUE constraint failed: Leverancier.leveranciernr

Accessoire uit AV

In [87]:
try:
    print("Start laden Accessoire")

    df = pd.read_sql("SELECT * FROM Accessoire", conn_av)
    print("Accessoire opgehaald | rijen:", len(df))

    df.to_sql("Accessoire", conn_sdm, if_exists="append", index=False)
    conn_sdm.commit()

    print("Accessoire succesvol geladen\n")

except Exception as e:
    print("FOUT bij Accessoire:", e, "\n")

Start laden Accessoire
Accessoire opgehaald | rijen: 10
FOUT bij Accessoire: UNIQUE constraint failed: Accessoire.accessoirenr

Fiets uit FV

In [88]:
try:
    print("Start laden Fiets")

    df = pd.read_sql("SELECT * FROM Fiets", conn_fv)
    print("Fiets opgehaald | rijen:", len(df))

    df.to_sql("Fiets", conn_sdm, if_exists="append", index=False)
    conn_sdm.commit()

    print("Fiets succesvol geladen\n")

except Exception as e:
    print("FOUT bij Fiets:", e, "\n")

Start laden Fiets
Fiets opgehaald | rijen: 75
FOUT bij Fiets: UNIQUE constraint failed: Fiets.fietsnr

Fabrikant uit FV

In [89]:
try:
    print("Start laden Fabrikant")

    df = pd.read_sql("SELECT * FROM Fabrikant", conn_fv)
    print("Fabrikant opgehaald | rijen:", len(df))

    df.to_sql("Fabrikant", conn_sdm, if_exists="append", index=False)
    conn_sdm.commit()

    print("Fabrikant succesvol geladen\n")

except Exception as e:
    print("FOUT bij Fabrikant:", e, "\n")

Start laden Fabrikant
Fabrikant opgehaald | rijen: 10
FOUT bij Fabrikant: UNIQUE constraint failed: Fabrikant.fabrikantnr

PROCES TABELLEN

Accessoire_verkoop

In [90]:
try:
    print("Start laden Accessoire_Verkoop")

    df = pd.read_sql("SELECT * FROM Accessoire_Verkoop", conn_av)
    print("Accessoire_Verkoop opgehaald | rijen:", len(df))

    df.to_sql("Accessoire_Verkoop", conn_sdm, if_exists="append", index=False)
    conn_sdm.commit()

    print("Accessoire_Verkoop succesvol geladen\n")

except Exception as e:
    print("FOUT bij Accessoire_Verkoop:", e, "\n")

Start laden Accessoire_Verkoop
Accessoire_Verkoop opgehaald | rijen: 100
FOUT bij Accessoire_Verkoop: UNIQUE constraint failed: Accessoire_Verkoop.accessoire_verkoopnr

Fiets_verkoop

In [91]:
try:
    print("Start laden Fiets_Verkoop")

    df = pd.read_sql("SELECT * FROM Fiets_Verkoop", conn_fv)
    print("Fiets_Verkoop opgehaald | rijen:", len(df))

    df.to_sql("Fiets_Verkoop", conn_sdm, if_exists="append", index=False)
    conn_sdm.commit()

    print("Fiets_Verkoop succesvol geladen\n")

except Exception as e:
    print("FOUT bij Fiets_Verkoop:", e, "\n")

Start laden Fiets_Verkoop
Fiets_Verkoop opgehaald | rijen: 150
FOUT bij Fiets_Verkoop: UNIQUE constraint failed: Fiets_Verkoop.fiets_verkoopnr

Onderhoud

In [92]:
try:
    print("Start laden Onderhoud")

    df = pd.read_sql("SELECT * FROM Onderhoud", conn_oh)
    print("Onderhoud opgehaald | rijen:", len(df))

    df.to_sql("Onderhoud", conn_sdm, if_exists="append", index=False)
    conn_sdm.commit()

    print("Onderhoud succesvol geladen\n")

except Exception as e:
    print("FOUT bij Onderhoud:", e, "\n")

Start laden Onderhoud
Onderhoud opgehaald | rijen: 50
FOUT bij Onderhoud: UNIQUE constraint failed: Onderhoud.onderhoudnr

Accessoire_Inkoop

In [93]:
try:
    print("Start laden Accessoire_Inkoop")

    df = pd.read_sql("SELECT * FROM Accessoire_Inkoop", conn_ai)
    print("Accessoire_Inkoop opgehaald | rijen:", len(df))

    df.to_sql("Accessoire_Inkoop", conn_sdm, if_exists="append", index=False)
    conn_sdm.commit()

    print("Accessoire_Inkoop succesvol geladen\n")

except Exception as e:
    print("FOUT bij Accessoire_Inkoop:", e, "\n")

Start laden Accessoire_Inkoop
Accessoire_Inkoop opgehaald | rijen: 50
FOUT bij Accessoire_Inkoop: UNIQUE constraint failed: Accessoire_Inkoop.inkoopnr

Fiets-Inkoop

In [94]:
try:
    print("Start laden Fiets_Inkoop")

    df = pd.read_sql("SELECT * FROM Fiets_Inkoop", conn_fi)
    print("Fiets_Inkoop opgehaald | rijen:", len(df))

    df.to_sql("Fiets_Inkoop", conn_sdm, if_exists="append", index=False)
    conn_sdm.commit()

    print("Fiets_Inkoop succesvol geladen\n")

except Exception as e:
    print("FOUT bij Fiets_Inkoop:", e, "\n")

Start laden Fiets_Inkoop
Fiets_Inkoop opgehaald | rijen: 100
FOUT bij Fiets_Inkoop: UNIQUE constraint failed: Fiets_Inkoop.inkoopnr

Controleren

In [95]:
print("Controle SDM:\n")

df1 = pd.read_sql("SELECT COUNT(*) as aantal FROM Klant", conn_sdm)
print("Klant:", df1["aantal"][0])

df2 = pd.read_sql("SELECT COUNT(*) as aantal FROM Fiets_Verkoop", conn_sdm)
print("Fiets_Verkoop:", df2["aantal"][0])

df3 = pd.read_sql("SELECT COUNT(*) as aantal FROM Onderhoud", conn_sdm)
print("Onderhoud:", df3["aantal"][0])

Controle SDM:

Klant: 21
Fiets_Verkoop: 150
Onderhoud: 50

Test data

In [96]:
df = pd.read_sql("SELECT COUNT(*) as aantal FROM Accessoire_Verkoop", conn_sdm)
print("Accessoire_Verkoop:", df["aantal"][0])

Accessoire_Verkoop: 100

In [80]:
pd.read_sql("SELECT COUNT(*) FROM Klant", conn_sdm)

   COUNT(*)
0        21

In [81]:
pd.read_sql("SELECT * FROM Klant WHERE klantnr = 0", conn_sdm)

   klantnr          naam       adres  woonplaats geslacht geboortedatum
0        0  Test persoon  TstStraat1  Zoetermeer        V    01-01-2000