# Werkcollege-opdrachten Week 1.3

## Dependencies importeren

Kopieer in het codeblok hieronder van het vorige werkcollege de import-code voor de dependencies die het vaakst worden gebruikt om data in te lezen. Geef er ook de gebruikelijke aliassen aan.<br>
Zet eventuele warnings uit.

In [20]:
import pandas as pd
import sqlite3
import warnings
warnings.simplefilter('ignore')

Zet de volgende bestanden in een makkelijk te vinden map, als je dat nog niet gedaan hebt:
- go_sales.sqlite
- go_crm.sqlite
- go_staff.sqlite

## Databasetabellen inlezen

Kopieer in het codeblok hieronder van het vorige werkcollege de code om een connectie met het bestand go_sales.sqlite te maken.

In [26]:
import sqlite3

conn = sqlite3.connect("data/go_sales.sqlite")

Lees van de ingelezen go_sales-database te volgende tabellen in met behulp van "SELECT * FROM *tabel*".
- product
- product_type
- product_line
- sales_staff
- sales_branch
- retailer_site
- country
- order_header
- order_details
- returned_item
- return_reason

In [ ]:

product = pd.read_sql_query("SELECT * FROM product", conn)
product_type = pd.read_sql_query("SELECT * FROM product_type", conn)
product_line = pd.read_sql_query("SELECT * FROM product_line", conn)
sales_staff = pd.read_sql_query("SELECT * FROM sales_staff", conn)
sales_branch = pd.read_sql_query("SELECT * FROM sales_branch", conn)
retailer_site = pd.read_sql_query("SELECT * FROM retailer_site", conn)
country = pd.read_sql_query("SELECT * FROM country", conn)
order_header = pd.read_sql_query("SELECT * FROM order_header", conn)
order_details = pd.read_sql_query("SELECT * FROM order_details", conn)
returned_item = pd.read_sql_query("SELECT * FROM returned_item", conn)
return_reason = pd.read_sql_query("SELECT * FROM return_reason", conn)

Krijg je een "no such table" error? Dan heb je misschien met .connect() per ongeluk een leeg  databasebestand (.sqlite) aangemaakt.<br> <u>Let op:</u> lees eventueel de informatie uit het vorige werkcollege nog eens goed door.

Als je tijdens onderstaande opdrachten uit het oog verliest welke tabellen er allemaal zijn, kan je deze Pythoncode uitvoeren:

In [30]:
sql_query = "SELECT * FROM sqlite_master WHERE type='table';"

pd.read_sql(sql_query, conn)

,type,name,tbl_name,rootpage,sql
0,table,country,country,480,"CREATE TABLE ""country"" (\n\t""COUNTRY_CODE""\tIN..."
1,table,order_details,order_details,11,"CREATE TABLE ""order_details"" (\n\t""ORDER_DETAI..."
2,table,order_header,order_header,24,"CREATE TABLE ""order_header"" (\n\t""ORDER_NUMBER..."
3,table,order_method,order_method,27,"CREATE TABLE ""order_method"" (\n\t""ORDER_METHOD..."
4,table,product,product,28,"CREATE TABLE ""product"" (\n\t""PRODUCT_NUMBER""\t..."
5,table,product_line,product_line,17,"CREATE TABLE ""product_line"" (\n\t""PRODUCT_LINE..."
6,table,product_type,product_type,10,"CREATE TABLE ""product_type"" (\n\t""PRODUCT_TYPE..."
7,table,retailer_site,retailer_site,18,"CREATE TABLE ""retailer_site"" (\n\t""RETAILER_SI..."
8,table,return_reason,return_reason,30,"CREATE TABLE ""return_reason"" (\n\t""RETURN_REAS..."
9,table,returned_item,returned_item,31,"CREATE TABLE ""returned_item"" (\n\t""RETURN_CODE..."
10,table,sales_branch,sales_branch,2,"CREATE TABLE ""sales_branch"" (\n\t""SALES_BRANCH..."
11,table,sales_staff,sales_staff,3,"CREATE TABLE ""sales_staff"" (\n\t""SALES_STAFF_C..."

Let op! Voor alle onderstaande opdrachten mag je <u>alleen Python</u> gebruiken, <u>geen SQL!</u>

## Selecties op één tabel zonder functies

Geef een overzicht met daarin de producten en hun productiekosten waarvan de productiekosten lager dan 100 dollar en hoger dan 50 dollar ligt. (2 kolommen, 23 rijen)

In [32]:
print(product.columns.tolist())

['PRODUCT_NUMBER', 'INTRODUCTION_DATE', 'PRODUCT_TYPE_CODE', 'PRODUCTION_COST', 'MARGIN', 'PRODUCT_IMAGE', 'LANGUAGE', 'PRODUCT_NAME', 'DESCRIPTION']

In [33]:
product_overzicht = product[["PRODUCT_NAME", "PRODUCTION_COST"]]

resultaat = product_overzicht[
    (product_overzicht["PRODUCTION_COST"] > 50) &
    (product_overzicht["PRODUCTION_COST"] < 100)
]

resultaat

                        PRODUCT_NAME  PRODUCTION_COST
5          TrailChef Deluxe Cook Set            85.11
7             TrailChef Double Flame            75.00
16                   Hibernator Lite            60.00
17                        Hibernator            86.00
19   Hibernator Self - Inflating Mat            78.55
22               Hibernator Camp Cot            65.33
23      Canyon Mule Climber Backpack            62.50
45           Granite Climbing Helmet            52.86
47             Husky Harness Extreme            55.00
57                    Granite Hammer            57.13
68                         Polar Ice            73.33
69                      Polar Sports            80.00
70                        Polar Wave            60.00
71                     Polar Extreme            72.50
74                      Edge Extreme            80.00
77                         Seeker 35            79.19
78                         Seeker 50            92.58
79                    Seeker Extreme            94.12
82                    Glacier Deluxe            56.25
83                       Glacier GPS            78.55
109                Blue Steel Putter            60.00
110            Blue Steel Max Putter            81.80
113              Course Pro Golf Bag            80.00

Geef een overzicht met daarin de producten en hun marge waarvan de marge lager dan 20 % of hoger dan 60 % ligt. (2 kolommen, 7 rijen)

In [34]:
product_marge = product[["PRODUCT_NAME", "MARGIN"]]

resultaat = product_marge[
    (product_marge["MARGIN"] < 20) |
    (product_marge["MARGIN"] > 60)
]

resultaat

                    PRODUCT_NAME  MARGIN
0            TrailChef Water Bag    0.33
1              TrailChef Canteen    0.23
2          TrailChef Kitchen Kit    0.28
3                  TrailChef Cup    0.28
4             TrailChef Cook Set    0.30
..                           ...     ...
110        Blue Steel Max Putter    0.55
111  Course Pro Golf and Tee Set    0.33
112          Course Pro Umbrella    0.50
113          Course Pro Golf Bag    0.60
114            Course Pro Gloves    0.50

[115 rows x 2 columns]

Geef een overzicht met daarin de landen waar met francs wordt betaald. Sorteer de uitkomst op land.  (1 kolom, 3 rijen)

In [36]:
landen = country[["COUNTRY", "CURRENCY_NAME"]]

resultaat = landen[
    landen["CURRENCY_NAME"].str.contains("franc")
]

resultaat = resultaat[["COUNTRY"]].sort_values("COUNTRY")

resultaat

        COUNTRY
15      Belgium
0        France
7   Switzerland

Geef een overzicht met daarin de verschillende introductiedatums waarop producten met meer dan 50% marge worden geïntroduceerd (1 kolom, 7 rijen)

In [38]:
resultaat = product[
    product["MARGIN"] > 0.50
][["INTRODUCTION_DATE"]]

resultaat = resultaat.drop_duplicates()

resultaat

    INTRODUCTION_DATE
66         2000-10-26
85         1995-02-15
101        2003-12-10
103        2003-12-18
104        2003-12-27
106        2004-01-13
110        2003-12-15

Geef een overzicht met daarin het eerste adres en de stad van verkoopafdelingen waarvan zowel het tweede adres als de regio bekend is (2 kolommen, 7 rijen)

In [39]:
resultaat = sales_branch[
    (sales_branch["ADDRESS2"].notna()) &
    (sales_branch["REGION"].notna())
][["ADDRESS1", "CITY"]]

resultaat

                            ADDRESS1              CITY
2                Singelgravenplein 4         Amsterdam
13  Prol. Paseo de la Reforma No. 51  Distrito Federal
14               202-2-3 Hyakunincho             Tokyo
15                     543-225 Asahi        Osaka City
16                  2315 Queen's Ave         Melbourne
18             Avenida Paulista, 333         São Paulo
24                    3 Albany Court        Birmingham

Geef een overzicht met daarin de landen waar met dollars (dollars of new dollar) wordt betaald. Sorteer de uitkomst op land. (1 kolom, 4 rijen)

In [40]:
resultaat = country[
    country["CURRENCY_NAME"].str.contains("dollar")
][["COUNTRY"]]

resultaat = resultaat.sort_values("COUNTRY")

resultaat

          COUNTRY
14      Australia
3          Canada
11         Taiwan
2   United States

Geef een overzicht met daarin beide adressen en de stad van vestigingen van klanten waarvan de postcode begint met een ‘D’ (van duitsland). Filter op vestigingen die een tweede adres hebben. (3 kolommen, 2 rijen)

In [41]:
resultaat = retailer_site[
    retailer_site["POSTAL_ZONE"].str.startswith("D") &
    retailer_site["ADDRESS2"].notna()
][["ADDRESS1", "ADDRESS2", "CITY"]]

resultaat

            ADDRESS1       ADDRESS2       CITY
31  Röntgenstraße 90  3. Tür rechts  Frankfurt
59   Grubesallee 141       4. Stock    Hamburg

## Selecties op één tabel met functies

Geef het totaal aantal producten dat is teruggebracht (1 waarde)

In [42]:
returned_item.shape[0]

619

Geef het aantal regio’s waarin verkoopafdelingen gevestigd zijn. (1 waarde)

In [43]:
sales_branch["REGION"].nunique()

15

Maak 3 variabelen:
- Een met de laagste
- Een met de hoogste
- Een met de gemiddelde (afgerond op 2 decimalen)

marge van producten (3 kolommen, 1 rij)

In [44]:
laagste_marge = product["MARGIN"].min()
hoogste_marge = product["MARGIN"].max()
gemiddelde_marge = round(product["MARGIN"].mean(), 2)

laagste_marge, hoogste_marge, gemiddelde_marge

(np.float64(0.17), np.float64(0.7), np.float64(0.4))

Geef het aantal vestigingen van klanten waarvan het 2e adres niet bekend is (1 waarde)

In [48]:
import sqlite3

go_crm = sqlite3.connect("data/go_crm.sqlite")

In [50]:
customer[customer["ADDRESS2"].isna()].shape[0]

286

Geef de gemiddelde kostprijs van de verkochte producten waarop korting (unit_sale_price < unit_price) is verleend (1 waarde)

In [54]:
import sqlite3

go_sales = sqlite3.connect("data/go_sales.sqlite")

In [57]:
sales = pd.read_sql_query("SELECT * FROM order_details", go_sales)

In [60]:
sales[sales["UNIT_SALE_PRICE"] < sales["UNIT_PRICE"]]["UNIT_PRICE"].mean()

np.float64(204.98742195283958)

In [61]:
round(sales[sales["UNIT_SALE_PRICE"] < sales["UNIT_PRICE"]]["UNIT_PRICE"].mean(), 2)

np.float64(204.99)

Geef een overzicht met daarin het aantal medewerkers per medewerkersfunctie (2 kolommen, 7 rijen)

In [62]:
staff = pd.read_sql_query("SELECT * FROM sales_staff", go_sales)

In [65]:
staff.groupby("POSITION_EN").size().reset_index(name="AANTAL")

                    POSITION_EN  AANTAL
0                Branch Manager      19
1              District Manager       4
2               General Manager       1
3  Level 1 Sales Representative      13
4  Level 2 Sales Representative      39
5  Level 3 Sales Representative      24
6              Regional Manager       2

Geef een overzicht met daarin per telefoonnummer het aantal medewerkers dat op dat telefoonnummer bereikbaar is. Toon alleen de telefoonnummer waarop meer dan 4 medewerkers bereikbaar zijn. (2 kolommen, 10 rijen)

In [67]:
resultaat = staff.groupby("WORK_PHONE").size().reset_index(name="AANTAL")

resultaat[resultaat["AANTAL"] > 4]

             WORK_PHONE  AANTAL
4     +(44) 121 3505267       5
10  +(61) 03 2982  4242       5
11  +31 (0)20 692 93 94       5
13    +33 1 68 94 52 20       5
18     1 (206) 292-0012       5
19     1 (305) 557-4810       6
20     1 (310) 281-5722       5
21     1 (403) 232-5986       5
22     1 (416) 493-5595       5
23     1 (617) 268-6754       6

## Selecties op meerdere tabellen zonder functies

Geef een overzicht met daarin het eerste adres en de stad van vestigingen van klanten uit ‘Netherlands’ (2 kolommen, 20 rijen)

In [ ]:
country = pd.read_sql("SELECT * FROM country", conn)
retailer_site = pd.read_sql("SELECT * FROM retailer_site", conn)

overzicht = retailer_site.merge(country, on="COUNTRY_CODE")
overzicht = overzicht.loc[overzicht["COUNTRY"] == "Netherlands", ["ADDRESS1", "CITY"]].head(20)

overzicht

                      ADDRESS1          CITY
240                   Beets 36         Beets
241               Perestraat 1      Deventer
242  Laan van Meerdervoort 966      Den Haag
243             Kalfjeslaan 47    Amstelveen
244               Startbaan 11    Amstelveen
245      Noorderspoorsingel 28     Groningen
246              Hogehilweg 13     Amsterdam
247             Spoorstraat 43    Varsseveld
248             Westhavenweg 8     Amsterdam
249              Westzeedijk 4        Muiden
250            Gooiergracht 91         Laren
251            Hoofdstraat 150   Pieterburen
252                Olde Diek 2         Laren
253     Amsterdamsestraatweg 8      Maarssen
254        Krayenhoffstraat 11     Amsterdam
255         Overschiestraat 19     Amsterdam
256              Havenbuurt 12        Marken
257               Duivendaal 1    Wageningen
258              Voorstraat 37  Nieuweschans
259         Stadhouderslaan 18     Rotterdam

Geef een overzicht met daarin de productnamen die tot het producttype ‘Eyewear’ behoren. (1 kolom, 5 rijen)

In [71]:
product = pd.read_sql("SELECT * FROM product", conn)
product_type = pd.read_sql("SELECT * FROM product_type", conn)

overzicht = product.merge(product_type, on="PRODUCT_TYPE_CODE")
overzicht = overzicht.loc[overzicht["PRODUCT_TYPE_EN"] == "Eyewear", ["PRODUCT_NAME"]].head(5)

overzicht

     PRODUCT_NAME
67      Polar Sun
68      Polar Ice
69   Polar Sports
70     Polar Wave
71  Polar Extreme

Geef een overzicht met daarin alle unieke eerste adressen van klantvestigingen en de voornaam en achternaam van de verkopers die ‘Branch Manager’ zijn en aan deze vestigingen hebben verkocht (3 kolommen, 1 rij)

In [72]:
retailer_site = pd.read_sql("SELECT * FROM retailer_site", conn)
order_header = pd.read_sql("SELECT * FROM order_header", conn)
sales_staff = pd.read_sql("SELECT * FROM sales_staff", conn)

overzicht = retailer_site.merge(order_header, on="RETAILER_SITE_CODE")
overzicht = overzicht.merge(sales_staff, on="SALES_STAFF_CODE")
overzicht = overzicht.loc[
    overzicht["POSITION_EN"] == "Branch Manager",
    ["ADDRESS1", "FIRST_NAME", "LAST_NAME"]
].drop_duplicates()

overzicht

                  ADDRESS1 FIRST_NAME LAST_NAME
3658  Alameda Santos, 9876     Bayard     Lopes

Geef een overzicht met daarin van de verkopers hun functie en indien zij iets hebben verkocht de datum waarop de verkoop heeft plaatsgevonden. Laat alleen de verschillende namen van de posities zien van de verkopers die het woord ‘Manager’ in hun positienaam hebben staan. (2 kolommen, 7 rijen)

In [73]:
sales_staff = pd.read_sql("SELECT * FROM sales_staff", conn)
order_header = pd.read_sql("SELECT * FROM order_header", conn)

overzicht = sales_staff.merge(order_header, on="SALES_STAFF_CODE", how="left")

overzicht = overzicht.loc[
    overzicht["POSITION_EN"].str.contains("Manager"),
    ["POSITION_EN", "ORDER_DATE"]
].drop_duplicates().head(7)

overzicht

           POSITION_EN  ORDER_DATE
0       Branch Manager         NaN
320   Regional Manager         NaN
648   District Manager         NaN
3748    Branch Manager  2024-09-09
3749    Branch Manager  2024-03-13
3750    Branch Manager  2024-01-09
4186   General Manager         NaN

Geef een overzicht met daarin de verschillende namen van producten en bijbehorende namen van producttypen van de producten waarvoor ooit meer dan 750 stuks tegelijk verkocht zijn. (2 kolommen, 9 rijen)

In [74]:
order_details = pd.read_sql("SELECT * FROM order_details", conn)
product = pd.read_sql("SELECT * FROM product", conn)
product_type = pd.read_sql("SELECT * FROM product_type", conn)

overzicht = order_details.merge(product, on="PRODUCT_NUMBER")
overzicht = overzicht.merge(product_type, on="PRODUCT_TYPE_CODE")

overzicht = overzicht.loc[
    overzicht["QUANTITY"] > 750,
    ["PRODUCT_NAME", "PRODUCT_TYPE_EN"]
].drop_duplicates().head(9)

overzicht

                PRODUCT_NAME    PRODUCT_TYPE_EN
539        BugShield Extreme  Insect Repellents
1759                Star Peg              Tents
20121  BugShield Lotion Lite  Insect Repellents
20147         Sun Shelter 15          Sunscreen
20152         Sun Shelter 30          Sunscreen
31236        BugShield Spray  Insect Repellents
37272              Firefly 2           Lanterns
37348       BugShield Lotion  Insect Repellents
37363             Sun Shield          Sunscreen

Geef een overzicht met daarin de productnamen waarvan ooit meer dan 40% korting is verleend. De formule voor korting is: (unit_price - unit_sale_price) / unit_price (1 kolom, 8 rijen)

In [75]:
order_details = pd.read_sql("SELECT * FROM order_details", conn)
product = pd.read_sql("SELECT * FROM product", conn)

overzicht = order_details.merge(product, on="PRODUCT_NUMBER")

overzicht["DISCOUNT"] = (overzicht["UNIT_PRICE"] - overzicht["UNIT_SALE_PRICE"]) / overzicht["UNIT_PRICE"]

overzicht = overzicht.loc[
    overzicht["DISCOUNT"] > 0.40,
    ["PRODUCT_NAME"]
].drop_duplicates().head(8)

overzicht

                      PRODUCT_NAME
506              BugShield Natural
511                BugShield Spray
650   Hailstorm Titanium Woods Set
2797         BugShield Lotion Lite
2836                Sun Shelter 30
3751             BugShield Extreme
5074                Sun Shelter 15
6930              BugShield Lotion

Geef een overzicht met daarin de retourreden van producten waarvan ooit meer dan 90% van de aangeschafte hoeveelheid is teruggebracht (return_quantity/quantity). (1 kolom, 3 rijen)

In [77]:
order_details = pd.read_sql("SELECT * FROM order_details", conn)
returned_item = pd.read_sql("SELECT * FROM returned_item", conn)
return_reason = pd.read_sql("SELECT * FROM return_reason", conn)

overzicht = order_details.merge(returned_item, on="ORDER_DETAIL_CODE")
overzicht = overzicht.merge(return_reason, on="RETURN_REASON_CODE")

overzicht["RETURN_PERCENT"] = overzicht["RETURN_QUANTITY"] / overzicht["QUANTITY"]

overzicht = overzicht.loc[
    overzicht["RETURN_PERCENT"] > 0.90,
    ["RETURN_DESCRIPTION_EN"]
].drop_duplicates().head(3)

overzicht

    RETURN_DESCRIPTION_EN
0   Wrong product ordered
4   Wrong product shipped
5  Unsatisfactory product

## Selecties op meerdere tabellen met functies

Geef een overzicht met daarin per producttype het aantal producten die tot dat producttype behoren. (2 kolommen, 21 rijen)

In [78]:
product = pd.read_sql("SELECT * FROM product", conn)
product_type = pd.read_sql("SELECT * FROM product_type", conn)

overzicht = product.merge(product_type, on="PRODUCT_TYPE_CODE")

overzicht = overzicht.groupby("PRODUCT_TYPE_EN")["PRODUCT_NUMBER"].count().reset_index()

overzicht

         PRODUCT_TYPE_EN  PRODUCT_NUMBER
0             Binoculars               4
1   Climbing Accessories               7
2           Cooking Gear              10
3                Eyewear               5
4              First Aid               5
5       Golf Accessories               4
6      Insect Repellents               5
7                  Irons               4
8                 Knives               5
9               Lanterns              12
10            Navigation               4
11                 Packs               6
12               Putters               3
13                  Rope               4
14                Safety               4
15         Sleeping Bags               7
16             Sunscreen               5
17                 Tents               6
18                 Tools               6
19               Watches               5
20                 Woods               4

Geef een overzicht met daarin per land het aantal vestigingen van klanten die zich in dat land bevinden. (2 kolommen, 21 rijen)

In [79]:
retailer_site = pd.read_sql("SELECT * FROM retailer_site", conn)
country = pd.read_sql("SELECT * FROM country", conn)

overzicht = retailer_site.merge(country, on="COUNTRY_CODE")

overzicht = overzicht.groupby("COUNTRY")["RETAILER_SITE_CODE"].count().reset_index()

overzicht

           COUNTRY  RETAILER_SITE_CODE
0        Australia                  10
1          Austria                  10
2          Belgium                  10
3           Brazil                   1
4           Canada                  31
5            China                  10
6          Denmark                   6
7          Finland                   5
8           France                  29
9          Germany                  32
10           Italy                  12
11           Japan                  25
12           Korea                  10
13          Mexico                  10
14     Netherlands                  20
15           Spain                   9
16          Sweden                  12
17     Switzerland                  13
18          Taiwan                  10
19  United Kingdom                  25
20   United States                 101

Geef een overzicht met daarin van de producten behorend tot het producttype ‘Cooking Gear’ per productnaam de totaal verkochte hoeveelheid en de gemiddelde verkoopprijs. Sorteer de uitkomst op totaal verkochte hoeveelheid. (6 kolommen, 10 rijen)

In [82]:
order_details = pd.read_sql("SELECT * FROM order_details", conn)
product = pd.read_sql("SELECT * FROM product", conn)
product_type = pd.read_sql("SELECT * FROM product_type", conn)

overzicht = order_details.merge(product, on="PRODUCT_NUMBER")
overzicht = overzicht.merge(product_type, on="PRODUCT_TYPE_CODE")

overzicht = overzicht.loc[overzicht["PRODUCT_TYPE_EN"] == "Cooking Gear"]

overzicht = overzicht.groupby(
    ["PRODUCT_NUMBER", "PRODUCT_NAME", "PRODUCT_TYPE_CODE", "PRODUCT_TYPE_EN"]
).agg({
    "QUANTITY": "sum",
    "UNIT_SALE_PRICE": "mean"
}).reset_index()

overzicht = overzicht.sort_values(by="QUANTITY", ascending=False)

overzicht.head(10)

,PRODUCT_NUMBER,PRODUCT_NAME,PRODUCT_TYPE_CODE,PRODUCT_TYPE_EN,QUANTITY,UNIT_SALE_PRICE
0,1,TrailChef Water Bag,1,Cooking Gear,36738,6.032506
3,4,TrailChef Cup,1,Cooking Gear,27418,6.976490
1,2,TrailChef Canteen,1,Cooking Gear,26544,11.979418
2,3,TrailChef Kitchen Kit,1,Cooking Gear,22206,22.345975
9,10,TrailChef Utensils,1,Cooking Gear,13776,17.294151
7,8,TrailChef Double Flame,1,Cooking Gear,12476,132.672882
4,5,TrailChef Cook Set,1,Cooking Gear,10878,51.687926
8,9,TrailChef Kettle,1,Cooking Gear,8826,12.201235
6,7,TrailChef Single Flame,1,Cooking Gear,8504,63.827622
5,6,TrailChef Deluxe Cook Set,1,Cooking Gear,3110,121.217638

Geef een overzicht met daarin per land de naam van het land, de naam van de stad waar de verkoopafdeling is gevestigd (noem de kolomnaam in het overzicht ‘verkoper’) en het aantal steden waar zich klanten bevinden in dat land (noem de kolomnaam in het overzicht ‘klanten’) (3 kolommen, 29 rijen)

In [84]:
sales_staff = pd.read_sql("SELECT * FROM sales_staff", conn)
sales_branch = pd.read_sql("SELECT * FROM sales_branch", conn)
country = pd.read_sql("SELECT * FROM country", conn)
retailer_site = pd.read_sql("SELECT * FROM retailer_site", conn)

verkopers = sales_staff.merge(sales_branch, on="SALES_BRANCH_CODE")
verkopers = verkopers.merge(country, on="COUNTRY_CODE")

klanten = retailer_site.merge(country, on="COUNTRY_CODE")
klanten_per_land = klanten.groupby("COUNTRY")["CITY"].nunique().reset_index()
klanten_per_land = klanten_per_land.rename(columns={"CITY": "klanten"})

overzicht = verkopers.merge(klanten_per_land, on="COUNTRY")
overzicht = overzicht.rename(columns={"CITY": "verkoper"})

overzicht = overzicht[["COUNTRY", "verkoper", "klanten"]].drop_duplicates()

overzicht

            COUNTRY          verkoper  klanten
0            France             Paris       14
4           Germany           Hamburg       18
8           Germany           München       18
11            Italy            Milano        9
14      Netherlands         Amsterdam       15
19           Sweden             Kista       10
23           Canada           Calgary       16
28           Canada           Toronto       16
33    United States            Boston       62
37    United States           Seattle       62
41    United States             Miami       62
45    United States       Los Angeles       62
55           France              Lyon       14
59           Mexico  Distrito Federal        6
62            Japan             Tokyo        5
64            Japan        Osaka City        5
66        Australia         Melbourne        6
71            Spain            Bilbao        5
73           Brazil         São Paulo        1
76          Finland            Kuopio        5
78            Korea             Seoul        6
80           Taiwan         San Chung        9
82            China          Shanghai        7
84   United Kingdom            London        9
88   United Kingdom        Birmingham        9
93      Switzerland            Zürich        9
96          Belgium          Heverlee        8
100         Austria              Wien        9

## Pythonvertalingen van SUBSELECT en UNION met o.a. for-loops

Geef een overzicht met daarin de voornaam en de achternaam van de medewerkers die nog nooit wat hebben verkocht (2 kolommen, 25 rijen)

In [85]:
sales_staff = pd.read_sql("SELECT * FROM sales_staff", conn)
order_header = pd.read_sql("SELECT * FROM order_header", conn)

verkopers_met_verkoop = order_header["SALES_STAFF_CODE"].unique()

overzicht = sales_staff[
    ~sales_staff["SALES_STAFF_CODE"].isin(verkopers_met_verkoop)
]

overzicht = overzicht[["FIRST_NAME", "LAST_NAME"]]

overzicht.head(25)

   FIRST_NAME      LAST_NAME
0       Denis           Pagé
5        Else         Mörike
6       Frank          Fuchs
9       Fritz         Hirsch
10       Jörg          Kunze
12      Maria      Iacobucci
17       Kick        Kalkman
22      Karin      Bergström
25      Sally          White
27      Frank        Bretton
28    Georges  Saint-Germain
33       Alex      Rodriguez
37   Samantha          Floyd
41      Julie          Olsen
45      Corey         Wright
51    Estelle        Johnson
52       Greg        Belding
55      Julie        Béchard
59      Lucía          Reyna
64     Kazumi        Uragome
66      Alice         Walter
84     Walter         Taylor
85   Penelope        Tamrine
88      Polly         Linton
96      Gracy        Gellens

Geef een overzicht met daarin het aantal producten waarvan de marge lager is dan de gemiddelde marge van alle producten samen. Geef in het overzicht tevens aan wat de gemiddelde marge is van dit aantal producten waarvan de marge lager dan de gemiddelde marge van alle producten samen is. (1 kolom, 2 rijen)

In [86]:
order_details = pd.read_sql("SELECT * FROM order_details", conn)

order_details["MARGE"] = order_details["UNIT_SALE_PRICE"] - order_details["UNIT_COST"]

gemiddelde_marge = order_details["MARGE"].mean()

lagere_marges = order_details[order_details["MARGE"] < gemiddelde_marge]

resultaat = pd.DataFrame({
    "resultaat": [
        lagere_marges["PRODUCT_NUMBER"].nunique(),
        lagere_marges["MARGE"].mean()
    ]
})

resultaat

    resultaat
0  105.000000
1   15.440326

Geef een overzicht met daarin de namen van de producten die voor meer dan 500 (verkoopprijs) zijn verkocht maar nooit zijn teruggebracht. (1 kolom, 13 rijen)

In [87]:
order_details = pd.read_sql("SELECT * FROM order_details", conn)
product = pd.read_sql("SELECT * FROM product", conn)
returned_item = pd.read_sql("SELECT * FROM returned_item", conn)

overzicht = order_details.merge(product, on="PRODUCT_NUMBER")

retour_codes = returned_item["ORDER_DETAIL_CODE"].unique()

overzicht = overzicht[
    (overzicht["UNIT_SALE_PRICE"] > 500) &
    (~overzicht["ORDER_DETAIL_CODE"].isin(retour_codes))
]

overzicht = overzicht[["PRODUCT_NAME"]].drop_duplicates()

overzicht.head(13)

                           PRODUCT_NAME
88                            Star Dome
95                         Star Gazer 2
103                        Star Gazer 3
112                        Star Gazer 6
616               Hailstorm Steel Irons
625            Hailstorm Titanium Irons
634          Lady Hailstorm Steel Irons
641       Lady Hailstorm Titanium Irons
647        Hailstorm Titanium Woods Set
657           Hailstorm Steel Woods Set
665   Lady Hailstorm Titanium Woods Set
674      Lady Hailstorm Steel Woods Set
1104                     Husky Rope 200

Geef een overzicht met daarin per (achternaam van) medewerker of hij/zij manager is of niet, door deze informatie toe te voegen als extra 'Ja/Nee'-kolom.<br>
Hint: gebruik een for-loop waarin je o.a. bepaalt of het woord 'Manager' in de functie (position_en) staat. (2 kolommen, 102 rijen).

In [88]:
sales_staff = pd.read_sql("SELECT * FROM sales_staff", conn)

manager_kolom = []

for positie in sales_staff["POSITION_EN"]:
    
    if "Manager" in positie:
        manager_kolom.append("Ja")
    else:
        manager_kolom.append("Nee")

sales_staff["manager"] = manager_kolom

overzicht = sales_staff[["LAST_NAME", "manager"]]

overzicht

     LAST_NAME manager
0         Pagé      Ja
1       Michel     Nee
2     Clermont     Nee
3       Jauvin     Nee
4    Wiesinger     Nee
..         ...     ...
97    Laermans     Nee
98     De Crée     Nee
99     Lattrez     Nee
100  Seefelder     Nee
101     Grüner     Nee

[102 rows x 2 columns]

Met de onderstaande code laat je Python het huidige jaar uitrekenen.

In [89]:
from datetime import date

huidig_jaar = date.today().year
huidig_jaar

2026

Met de onderstaande code selecteer je op een bepaald jaartal uit een datum.

In [3]:
from datetime import datetime

date_str = '16-8-2013'
date_format = '%d-%m-%Y'
date_obj = datetime.strptime(date_str, date_format)

date_obj.year

2013

Geef met behulp van bovenstaande hulpcode een overzicht met daarin op basis van het aantal jaar dat iemand in dienst is of een medewerker ‘kort in dienst’ (minder dan 30 jaar in dienst) of een ‘lang in dienst’ (groter dan gelijk aan 30 jaar in dienst) is. Geef daarbij per medewerker in een aparte kolom zowel ‘kort in dienst’ als ‘lang in dienst’ aan. Gebruik (wederom) een for-loop.<br>
(2 kolommen, 102 rijen)

In [91]:
from datetime import datetime
from datetime import date

sales_staff = pd.read_sql("SELECT * FROM sales_staff", conn)

huidig_jaar = date.today().year

dienst_status = []

for datum in sales_staff["DATE_HIRED"]:
    
    date_str = datum
    date_format = "%Y-%m-%d"
    
    date_obj = datetime.strptime(date_str, date_format)
    
    jaren_in_dienst = huidig_jaar - date_obj.year
    
    if jaren_in_dienst < 30:
        dienst_status.append("kort in dienst")
    else:
        dienst_status.append("lang in dienst")

sales_staff["diensttijd"] = dienst_status

overzicht = sales_staff[["LAST_NAME", "diensttijd"]]

overzicht

     LAST_NAME      diensttijd
0         Pagé  lang in dienst
1       Michel  lang in dienst
2     Clermont  kort in dienst
3       Jauvin  kort in dienst
4    Wiesinger  kort in dienst
..         ...             ...
97    Laermans  kort in dienst
98     De Crée  kort in dienst
99     Lattrez  kort in dienst
100  Seefelder  kort in dienst
101     Grüner  kort in dienst

[102 rows x 2 columns]