# Werkcollege-opdrachten Week 1.1

## Maak een virtual environment

Zorg dat je met behulp van de handleiding *Bouw en gebruik van virtual environments - Handleiding* een virtual environment hebt gemaakt, dat jou en je duopartner garandeert altijd dezelfde versie van geïmporteerde dependencies te gebruiken.<br>
Voeg hier vervolgens de pandas- en de sqlite3-dependency aan toe.<br>
Als je dit allemaal goed hebt gedaan moet de onderstaande code bij jullie allebei succesvol runnen:

In [ ]:
import pandas as pd
import sqlite3
import warnings
warnings.simplefilter('ignore')

N.B.: de 2 reeds geschreven coderegels zorgen ervoor dat eventuele warnings, die code-outputs lelijker maken, uitgezet worden.

Zorg er daarnaast voor dat je...
- Het bestand Waarheidstabel.png in dezelfde map als dit notebook hebt staan.
- Het bestand Prinstabel.png in dezelfde map als dit notebook hebt staan.
- Alle informatie onder het kopje *Basisoperaties* van de cheatsheet *Van Java naar Python - Cheatsheet* bij de hand hebt.

## Output, variabelen en input

Geef code waarmee het volgende op het scherm komt te staan:<br>
geef me je geld <br>
of ik gebruik geweld, <br>
toen kwam de controle aangesneld

In [ ]:
print("geef me je geld")
print("of ik gebruik geweld,")
print("toen kwam de controle aangesneld")

geef me je geld
of ik gebruik geweld,
toen kwam de controle aangesneld

Declareer 2 variabelen zodat de volgende tekst geprint wordt:<br>
Apenhoofd<br>
Paardenstaart

In [ ]:
woord1 = "Apenhoofd"
woord2 = "Paardenstaart"

print(woord1)
print(woord2)

Apenhoofd
Paardenstaart

Voeg code toe zodat het programma het volgende doet:<br>
1): Op het scherm komt A, B, C, D, ..., F, G te staan<br>
2): De gebruiker voert een letter in<br>
3): Op het scherm komt te staan:<br>
Het is inderdaad:<br>
*ingevoerde letter*

In [ ]:
print("A, B, C, D, ..., F, G")

letter = "D"   

print("Het is inderdaad:")
print(letter)

A, B, C, D, ..., F, G
Het is inderdaad:
D

## Stringconcatenatie en Rekenen

Schrijf code dat een inkomen inleest en het volgende uitprint:<br>
Uw inkomen (*ingelezen inkomen*) is zeer acceptabel.

In [ ]:
inkomen = input("Voer uw inkomen in: ")

print("Uw inkomen " + inkomen + " is zeer acceptabel.")

De oppervlakte van een driehoek is 1/2 * hoogte * basis<br>
Schrijf code zodat het programma het volgende doet:<br>
1): Op het scherm komt Wat is de basis? te staan<br>
2): De gebruiker voert een basis in<br>
3): Op het scherm komt Wat is de hoogte? te staan<br>
4): De gebruiker voert een hoogte in<br>
5): Op het scherm komt: De oppervlakte van de driehoek is *berekende oppervlakte* te staan

In [ ]:
print("Wat is de basis?")
basis = float(input())

print("Wat is de hoogte?")
hoogte = float(input())

oppervlakte = 0.5 * hoogte * basis

print(f"De oppervlakte van de driehoek is {oppervlakte}")

## if() en booleans

Schrijf code dat het volgende doet:<br>
1): De gebruiker voert in hoe oud iemand is<br>
2): De gebruiker voert in of de ouders meegekomen zijn (input is J of N)<br><br>

Als...
- Jonger dan 6, wel ouders: op het scherm staat Je mag het zwembad in
- Jonger dan 6, geen ouders: op het scherm staat Je mag het niet zwembad in
- Leeftijd vanaf 6, geen ouders: op het scherm staat Je mag het zwembad in als je een diploma hebt
- Leeftijd vanaf 6, wel ouders: op het scherm staat Waarom neem je nog je ouders mee?

In [ ]:
leeftijd = int(input("Hoe oud ben je? "))
ouders = input("Zijn je ouders meegekomen? (J/N): ")

if leeftijd < 6 and ouders == "J":
    print("Je mag het zwembad in")

elif leeftijd < 6 and ouders == "N":
    print("Je mag het zwembad niet in")

elif leeftijd >= 6 and ouders == "N":
    print("Je mag het zwembad in als je een diploma hebt")

elif leeftijd >= 6 and ouders == "J":
    print("Waarom neem je nog je ouders mee?")

Schrijf code zodat de boolean-variabelen een en twee aangemaakt worden en waarmee de juiste waarde in de boolean-variabele uitkomst komt te staan. In de waarheidstabel hieronder staat wat de waarde van uitkomst is bij de verschillende mogelijke combinaties van een en twee.<br><br>
<img src="Waarheidstabel.png">

In [ ]:
een = True
twee = False

uitkomst = (not een) or twee

print(uitkomst)

## Functies

Schrijf een methode wachtwoord die als parameters twee woorden meekrijgt en het volgende controleert:
- Als de woorden gelijk zijn, print het programma gelijk.
- Als de woorden ongelijk zijn print het programma ongelijk.

Vergeet niet dat je de methode niet alleen aan moet maken, maar ook aan moet roepen om output te krijgen.

In [ ]:
def wachtwoord(woord1, woord2):

    if woord1 == woord2:
        print("gelijk")

    else:
        print("ongelijk")


wachtwoord("appel", "appel")

Schrijf de methode zoekPrins die als parameter een prinses meekrijgt en vervolgens de bijbehorende prins oplevert, volgens de volgende tabel:<br><br>
<img src="Prinstabel.png"><br>
Als de naam van de prinses niet in de tabel staat wordt het volgende door de methode teruggegeven: naamloos.<br>
Roep ten slotte de gemaakte methode ook daadwerkelijk aan met een zelfgekozen prinsessennaam.

In [ ]:
def zoekPrins(prinses):

    prinsen = {
        "Aurora": "Philip",
        "Ariël": "Eric",
        "Jasmine": "Aladdin",
        "Pocahontas": "John",
        "Belle": "Beast",
        "Tiana": "Naveen",
        "Mulan": "Shang"
    }

    if prinses in prinsen:
        return prinsen[prinses]
    else:
        return "naamloos"


resultaat = zoekPrins("Belle")
print(resultaat)

## While-loop

Schrijf de inhoud van de methode wachtwoord. Deze heeft geen parameters en laat de gebruiker twee wachtwoorden invoeren, waarna hij bekijkt of deze gelijk zijn. Zolang dat niet het geval is wordt er eerst Fout, probeer het opnieuw! uitgeprint en moet de gebruiker het opnieuw proberen.<br>Als de gebruiker het goed doet, komt er Succes! op het scherm te staan.

In [ ]:
def wachtwoord():

    w1 = input("Voer wachtwoord in: ")
    w2 = input("Herhaal wachtwoord: ")

    while w1 != w2:
        print("Fout, probeer het opnieuw!")

        w1 = input("Voer wachtwoord in: ")
        w2 = input("Herhaal wachtwoord: ")

    print("Succes!")



wachtwoord()

Schrijf de inhoud van de methode tafels. De methode print alle tafels vanaf 1 (dus inclusief de tafel van 1) tot en met de tafel van het meegekregen getal (dus inclusief de tafel van getal).  Zet een witregel tussen alle tafels in. <br>
Let op:
- Gebruik een while-loop
- Gebruik de reeds geschreven methode tafel om een tafel uit te printen

In [ ]:
def tafel(getal: int):
    teller: int = 1

    while teller <= 10:
        print(f'{teller} x {getal} = {teller * getal}')
        teller += 1


def tafels(getal: int):
    nummer: int = 1

    while nummer <= getal:
        tafel(nummer)
        print()
        nummer += 1


x: int = int(input())
tafels(x)

## For-loop

Vervang de while-loop door een werkende for-loop. De uitkomst van het programma mag daarbij niet veranderen.

In [9]:
def loopje():

    for aantal in range(0, 11):
        print(f"huidige getal: {aantal}")

loopje()

huidige getal: 0
huidige getal: 1
huidige getal: 2
huidige getal: 3
huidige getal: 4
huidige getal: 5
huidige getal: 6
huidige getal: 7
huidige getal: 8
huidige getal: 9
huidige getal: 10

Schrijf de methode checkEven die achtereenvolgens 12 getallen inleest en afdrukt hoe vaak het ingevoerde getal even was.

In [ ]:
def checkEven():

    teller_even = 0

    for i in range(12):
        getal = int(input("Voer een getal in: "))

        if getal % 2 == 0:
            teller_even += 1

    print(f"Het aantal even getallen is: {teller_even}")


checkEven()

## Objectoriëntatie

Maak een minisysteem voor een kledingwinkel. Maak verschillende klassen voor verschillende soorten kledingstukken, waarbij sommige klassen geërfd worden van andere klassen.
- Maak een klasse Kledingstuk aan, waarin door de constructor een merk, een maat en een prijs geïnitialiseerd worden.
- Maak een klasse Broek en een klasse Shirt, beide erven van de klasse Kledingstuk. Voeg aan Broek een broek_type, en aan Shirt een shirt_type toe (d.m.v. constructorgebruik).
- Maak een klasse Spijkerbroek die erft van broek en een klasse Poloshirt die erft van shirt. Voeg aan Spijkerbroek een blauwtint toe, en aan Poloshirt een kraagsoort (d.m.v. constructorgebruik).
- Implementeer in elke klasse een beschrijvingmethode, waarmee alle informatie over het betreffende kledingstuk wordt afgedrukt.
- Maak van elke klasse een object aan en roep de beschrijvingmethode aan. Controleer nauwkeurig of alles naar behoren werkt.

In [1]:
class Kledingstuk:
    def __init__(self, merk, maat, prijs):
        self.merk = merk
        self.maat = maat
        self.prijs = prijs

    def beschrijving(self):
        print(f"Merk: {self.merk}, Maat: {self.maat}, Prijs: €{self.prijs}")


class Broek(Kledingstuk):
    def __init__(self, merk, maat, prijs, broek_type):
        super().__init__(merk, maat, prijs)
        self.broek_type = broek_type

    def beschrijving(self):
        print(f"Merk: {self.merk}, Maat: {self.maat}, Prijs: €{self.prijs}, Broek type: {self.broek_type}")


class Shirt(Kledingstuk):
    def __init__(self, merk, maat, prijs, shirt_type):
        super().__init__(merk, maat, prijs)
        self.shirt_type = shirt_type

    def beschrijving(self):
        print(f"Merk: {self.merk}, Maat: {self.maat}, Prijs: €{self.prijs}, Shirt type: {self.shirt_type}")


class Spijkerbroek(Broek):
    def __init__(self, merk, maat, prijs, broek_type, blauwtint):
        super().__init__(merk, maat, prijs, broek_type)
        self.blauwtint = blauwtint

    def beschrijving(self):
        print(f"Merk: {self.merk}, Maat: {self.maat}, Prijs: €{self.prijs}, Broek type: {self.broek_type}, Blauwtint: {self.blauwtint}")


class Poloshirt(Shirt):
    def __init__(self, merk, maat, prijs, shirt_type, kraagsoort):
        super().__init__(merk, maat, prijs, shirt_type)
        self.kraagsoort = kraagsoort

    def beschrijving(self):
        print(f"Merk: {self.merk}, Maat: {self.maat}, Prijs: €{self.prijs}, Shirt type: {self.shirt_type}, Kraagsoort: {self.kraagsoort}")


kledingstuk = Kledingstuk("Nike", "M", 29.99)
broek = Broek("Levi's", "L", 59.99, "chino")
shirt = Shirt("Adidas", "S", 24.99, "t-shirt")
spijkerbroek = Spijkerbroek("G-Star", "M", 79.99, "jeans", "donkerblauw")
poloshirt = Poloshirt("Tommy Hilfiger", "L", 49.99, "polo", "klassieke kraag")

kledingstuk.beschrijving()
broek.beschrijving()
shirt.beschrijving()
spijkerbroek.beschrijving()
poloshirt.beschrijving()

Merk: Nike, Maat: M, Prijs: €29.99
Merk: Levi's, Maat: L, Prijs: €59.99, Broek type: chino
Merk: Adidas, Maat: S, Prijs: €24.99, Shirt type: t-shirt
Merk: G-Star, Maat: M, Prijs: €79.99, Broek type: jeans, Blauwtint: donkerblauw
Merk: Tommy Hilfiger, Maat: L, Prijs: €49.99, Shirt type: polo, Kraagsoort: klassieke kraag

## Verzamelingen

Kijk nu naar alle info onder het kopje *Verzamelingen* van de cheatsheet *Van Java naar Python - Cheatsheet*.

Initialiseer een lijst met de naam mijn_lijst met de volgende waarden:<br>
Jelle, Marleen, Henk, Fatima, Jelle, Henk

In [3]:
mijn_lijst = ["Jelle", "Marleen", "Henk", "Fatima", "Jelle", "Henk"]

Probeer nu de eerste waarde uit te lijst te veranderen in een naam naar keuze. Lukt dat?

In [4]:
mijn_lijst[0] = "Sofia"

Maak van bovengenoemde lijst nu een tupel, genaamd: mijn_tupel.

In [5]:
mijn_tupel = tuple(mijn_lijst)

Probeer nu de laatste waarde uit te tupel te veranderen in een naam naar keuze. Lukt dat?

In [6]:
mijn_tupel[-1] = "Sofia"

TypeError: 'tuple' object does not support item assignment

Initialiseer een dictionary met de volgende key-value-combinaties:
- naam: "Jelle"
- leeftijd: 30
- beroep: "Docent"
- hobby: "Volleybal"

In [7]:
mijn_dict = {
    "naam": "Jelle",
    "leeftijd": 30,
    "beroep": "Docent",
    "hobby": "Volleybal"
}

Probeer nu de naam te veranderen naar een naam naar keuze. Lukt dat?

In [8]:
mijn_dict["naam"] = "Sofia"

## Data klaarzetten

Zet de volgende bestanden in een makkelijk terug te vinden map:
- go_sales.sqlite
- go_crm.sqlite
- go_staff.sqlite

Bestudeer de bovenste 3 bestanden met DB Browser (SQLite) dat <a href="https://sqlitebrowser.org/dl/">hier</a> te downloaden is. Wat valt je op qua datatypen?<br>

## Databasetabel inlezen

Creëer een databaseconnectie met het bestand go_sales.sqlite. Let op: deze staat in de map "data", die op zijn beurt in de hoofdmap staat. Tip: met `"../"` in `connect()` kun je naar de bovenliggende map gaan.

In [9]:
import sqlite3

conn = sqlite3.connect("data/go_sales.sqlite")

<b>Let goed op:</b><br>
Als je per ongeluk een verkeerde bestandsnaam ingeeft, maakt Python zélf een leeg databasebestand aan! Er ontstaat dan dus een nieuwe .sqlite, en dat is nadrukkelijk <u>niet de bedoeling.</u>

Gebruik de onderstaande sql_query om te achterhalen welke databasetabellen in go_sales zitten.

In [10]:
import sqlite3

conn = sqlite3.connect("data/go_sales.sqlite")

sql_query = "SELECT name FROM sqlite_master WHERE type='table';"

cursor = conn.cursor()
cursor.execute(sql_query)

tables = cursor.fetchall()
print(tables)

[('country',), ('order_details',), ('order_header',), ('order_method',), ('product',), ('product_line',), ('product_type',), ('retailer_site',), ('return_reason',), ('returned_item',), ('sales_branch',), ('sales_staff',)]

Krijg je lege output? Dan heb je per ongeluk een leeg  databasebestand (.sqlite) aangemaakt.<br>
Lees de informatie onder het kopje <b>Let goed op:</b> hierboven nog eens goed door.

Gebruik de gecreëerde databaseconnectie om de resultaten van de volgende query in een DataFrame te zetten:<br>
*SELECT * FROM sales_staff*

In [11]:
import pandas as pd

query = "SELECT * FROM sales_staff"

df = pd.read_sql_query(query, conn)

df

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE
0,4,Denis,Pagé,Branch Manager,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,1995-06-08,6
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,1997-08-16,6
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13
...,...,...,...,...,...,...,...,...,...,...
97,120,Giele,Laermans,Level 1 Sales Representative,+32 16 20.73.21,1340.0,+32 16 20.73.32,GLaermans@grtd123.com,1999-11-15,38
98,121,François,De Crée,Level 1 Sales Representative,+32 16 20.73.21,1642.0,+32 16 20.73.32,FDecree@grtd123.com,1999-12-01,38
99,122,Yvette,Lattrez,Level 3 Sales Representative,+32 16 20.73.21,1633.0,+32 16 20.73.32,YLattrez@grtd123.com,1999-12-09,38
100,123,Willi,Seefelder,Level 2 Sales Representative,+(43) 13 79 56 32,325.0,+(43) 13 79 56 33,WSeefelder@grtd123.com,1998-10-28,39
101,124,Sabine,Grüner,Level 3 Sales Representative,+(43) 13 79 56 32,348.0,+(43) 13 79 56 33,SGruner@grtd123.com,1998-02-18,39

## Datumkolommen afhandelen

Zoals je misschien al hebt gezien in DB Browser, zijn datums als TEXT opgeslagen, en niet als DATE, DATETIME o.i.d. Hier moeten we dus nog even "typische datumkolommen" van maken. Dat doen we met de volgende code:

In [12]:
df['DATE_HIRED'] = pd.to_datetime(df['DATE_HIRED'])
df.dtypes

SALES_STAFF_CODE              int64
FIRST_NAME                   object
LAST_NAME                    object
POSITION_EN                  object
WORK_PHONE                   object
EXTENSION                   float64
FAX                          object
EMAIL                        object
DATE_HIRED           datetime64[ns]
SALES_BRANCH_CODE             int64
dtype: object

Als we hier het jaar uit willen halen, schrijven we:

In [13]:
pd.DatetimeIndex(df['DATE_HIRED']).year

Index([1996, 1995, 1998, 1997, 1997, 1999, 1997, 1998, 1996, 1996,
       ...
       1998, 2000, 1999, 2000, 1999, 1999, 1999, 1999, 1998, 1998],
      dtype='int32', name='DATE_HIRED', length=102)

Deze zelfde syntax is te gebruiken voor het extraheren van kwartalen, maanden, weken en dagen. Probeer het maar eens!

## DataFrames uitsplitsen en opbouwen met Series

De volgende 5 kolommen hebben betrekking op de contactdetails van elke medewerker in dit DataFrame:
- SALES_STAFF_CODE
- WORK_PHONE
- EXTENSION
- FAX
- EMAIL

Maak van elk van deze 5 kolommen een serie.

In [14]:
sales_staff_code = df['SALES_STAFF_CODE']
work_phone = df['WORK_PHONE']
extension = df['EXTENSION']
fax = df['FAX']
email = df['EMAIL']

Zet allevijf gecreëerde series als kolommen naast elkaar in een DataFrame (*contact_details*). Gebruik pd.concat(...)<br>
Hulpvraag: welke waarde geef je aan de axis-parameter?

In [15]:
contact_details = pd.concat(
    [sales_staff_code, work_phone, extension, fax, email],
    axis=1
)

contact_details

,SALES_STAFF_CODE,WORK_PHONE,EXTENSION,FAX,EMAIL
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com
...,...,...,...,...,...
97,120,+32 16 20.73.21,1340.0,+32 16 20.73.32,GLaermans@grtd123.com
98,121,+32 16 20.73.21,1642.0,+32 16 20.73.32,FDecree@grtd123.com
99,122,+32 16 20.73.21,1633.0,+32 16 20.73.32,YLattrez@grtd123.com
100,123,+(43) 13 79 56 32,325.0,+(43) 13 79 56 33,WSeefelder@grtd123.com
101,124,+(43) 13 79 56 32,348.0,+(43) 13 79 56 33,SGruner@grtd123.com

## Series en DataFrames maken vanuit lists en dictionaries

Met .head(*getal*) kan je de bovenste *getal* rijen van een tabel selecteren.<br>
Selecteer op deze manier de bovenste 5 rijen van *contact_details*.<br>
Sla dit resultaat op in een nieuw DataFrame.

In [16]:
contact_top5 = contact_details.head(5)

contact_top5

,SALES_STAFF_CODE,WORK_PHONE,EXTENSION,FAX,EMAIL
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com

Aan deze 10 rijen met contactdetails willen we 3 kolommen toevoegen: 'FIRST_LANGUAGE', 'SECOND_LANGUAGE' & 'THIRD_LANGUAGE'.<br>
Iedereens 'First Language' is Engels, afgekort 'EN'. Maak een lijst waarin 5x 'EN' staat.<br>
Converteer deze lijst vervolgens naar een serie en voeg deze horizontaal samen met het resultaat van de vorige opdracht.<br>
Vergeet niet een passende naam te geven aan de nieuw ontstane kolom.

In [17]:
first_language_list = ['EN'] * 5

first_language_series = pd.Series(first_language_list, name='FIRST_LANGUAGE')

contact_top5 = pd.concat([contact_top5, first_language_series], axis=1)

contact_top5

,SALES_STAFF_CODE,WORK_PHONE,EXTENSION,FAX,EMAIL,FIRST_LANGUAGE
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,EN
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,EN
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,EN
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,EN
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,EN

Maak nu de tweede kolom ('SECOND_LANGUAGE'). Maak daarvoor een dictionary, met daarin...
- Als keys: alle indexen uit het resultaat van het vorige codeblok.
- Als values: bij de eerste 3 elementen 'FR' (Frankrijk), bij de laatste 2 'DE' (Duitsland).

Maak vervolgens ook hier weer een serie van en voeg ook deze weer horizontaal samen met het rsultaat van de vorige opdracht.<br>
Vergeet niet een passende naam te geven aan de nieuw ontstane kolom.

In [18]:
second_language_dict = {
    contact_top5.index[0]: 'FR',
    contact_top5.index[1]: 'FR',
    contact_top5.index[2]: 'FR',
    contact_top5.index[3]: 'DE',
    contact_top5.index[4]: 'DE'
}

second_language_series = pd.Series(second_language_dict, name='SECOND_LANGUAGE')

contact_top5 = pd.concat([contact_top5, second_language_series], axis=1)

contact_top5

,SALES_STAFF_CODE,WORK_PHONE,EXTENSION,FAX,EMAIL,FIRST_LANGUAGE,SECOND_LANGUAGE
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,EN,FR
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,EN,FR
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,EN,FR
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,EN,DE
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,EN,DE

Maak ten slotte de derde kolom ('THIRD_LANGUAGE') door een dictionary te maken met daarin...
- Als key: de naam van de nieuwe kolom. Zie je het verschil qua keys met de vorige opdracht?
- Als waarde: een lijst met daarin 'NL', 'NL', 'JPN', 'JPN', 'KOR'.

Converteer deze dictionary nu naar een DataFrame en voeg deze horizontaal samen met het resultaat van de vorige opdracht.<br>
Waarom hoef je hierna de nieuw ontstane kolom geen passende naam meer te geven?

In [19]:
third_language_dict = {
    'THIRD_LANGUAGE': ['NL', 'NL', 'JPN', 'JPN', 'KOR']
}

third_language_df = pd.DataFrame(third_language_dict)

contact_top5 = pd.concat([contact_top5, third_language_df], axis=1)

contact_top5

,SALES_STAFF_CODE,WORK_PHONE,EXTENSION,FAX,EMAIL,FIRST_LANGUAGE,SECOND_LANGUAGE,THIRD_LANGUAGE
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,EN,FR,NL
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,EN,FR,NL
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,EN,FR,JPN
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,EN,DE,JPN
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,EN,DE,KOR

## Data toevoegen

### Rijen

Gebruik de originele databasetabel *sales_staff*.<br>
Voeg een extra rij toe met eigen invulling. Zorg ervoor dat de index netjes doorloopt.<br>
Hulpvraag: welke waarde geef je nu aan axis?

In [20]:
new_row = pd.DataFrame([{
    'SALES_STAFF_CODE': 999,
    'FIRST_NAME': 'Sofia',
    'LAST_NAME': 'Test',
    'POSITION_EN': 'Sales Representative',
    'WORK_PHONE': '+31 000000000',
    'EXTENSION': None,
    'FAX': None,
    'EMAIL': 'sofia@test.com',
    'DATE_HIRED': pd.to_datetime('2024-01-01'),
    'SALES_BRANCH_CODE': 1
}])

df = pd.concat([df, new_row], axis=0, ignore_index=True)

df.tail()

/var/folders/7m/rsq396l90h71hq4ws0gkrqfw0000gn/T/ipykernel_1124/2246402582.py:14: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, new_row], axis=0, ignore_index=True)

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE
98,121,François,De Crée,Level 1 Sales Representative,+32 16 20.73.21,1642.0,+32 16 20.73.32,FDecree@grtd123.com,1999-12-01,38
99,122,Yvette,Lattrez,Level 3 Sales Representative,+32 16 20.73.21,1633.0,+32 16 20.73.32,YLattrez@grtd123.com,1999-12-09,38
100,123,Willi,Seefelder,Level 2 Sales Representative,+(43) 13 79 56 32,325.0,+(43) 13 79 56 33,WSeefelder@grtd123.com,1998-10-28,39
101,124,Sabine,Grüner,Level 3 Sales Representative,+(43) 13 79 56 32,348.0,+(43) 13 79 56 33,SGruner@grtd123.com,1998-02-18,39
102,999,Sofia,Test,Sales Representative,+31 000000000,NaN,None,sofia@test.com,2024-01-01,1

### Kolommen

Voeg een kolom *FULL_NAME* toe die de waarden van *FIRST_NAME* en *LAST_NAME* achter elkaar zet, gescheiden door een spatie.

In [21]:
df['FULL_NAME'] = df['FIRST_NAME'] + ' ' + df['LAST_NAME']

df.head()

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE,FULL_NAME
0,4,Denis,Pagé,Branch Manager,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6,Denis Pagé
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,1995-06-08,6,Élizabeth Michel
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6,Émile Clermont
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,1997-08-16,6,Étienne Jauvin
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13,Elsbeth Wiesinger

## Data wijzigen

### Datatypen

Door het attribuut .dtypes van een DataFrame op te vragen krijg je een serie die per kolom het datatype weergeeft. Doe dit bij de originele databasetabel *sales_staff*

In [22]:
df.dtypes

SALES_STAFF_CODE              int64
FIRST_NAME                   object
LAST_NAME                    object
POSITION_EN                  object
WORK_PHONE                   object
EXTENSION                   float64
FAX                          object
EMAIL                        object
DATE_HIRED           datetime64[ns]
SALES_BRANCH_CODE             int64
FULL_NAME                    object
dtype: object

Hier valt op dat elke kolom het datatype 'object' heeft: Python leest dus alles als string. Wiskundige operaties zijn hierdoor niet mogelijk.<br>
We kunnen proberen om kolommen met getallen, bijvoorbeeld de 'extension', te converteren naar een int. Zie onderstaande code.

In [24]:
df['EXTENSION'] = df['EXTENSION'].fillna(0).astype(int)

df.dtypes

SALES_STAFF_CODE              int64
FIRST_NAME                   object
LAST_NAME                    object
POSITION_EN                  object
WORK_PHONE                   object
EXTENSION                     int64
FAX                          object
EMAIL                        object
DATE_HIRED           datetime64[ns]
SALES_BRANCH_CODE             int64
FULL_NAME                    object
dtype: object

Dit lukt echter niet, omdat er in de kolom 'EXTENSION' lege waarden zitten die niet geconverteerd kunnen worden naar een int.<br>
Wél kan je deze naar een float converteren, zie onderstaande code:

In [25]:
df['EXTENSION'] = df['EXTENSION'].astype(float)

df.dtypes

SALES_STAFF_CODE              int64
FIRST_NAME                   object
LAST_NAME                    object
POSITION_EN                  object
WORK_PHONE                   object
EXTENSION                   float64
FAX                          object
EMAIL                        object
DATE_HIRED           datetime64[ns]
SALES_BRANCH_CODE             int64
FULL_NAME                    object
dtype: object

Als we in de rij van 'EXTENSION' kijken zien we dat de conversie van het datatype nu is gelukt.<br>
Dit is <b>randvoorwaardelijk</b> voor het uitvoeren van wiskundige operaties.<br>

### Rijen

Zorg er nu voor dat bij alle extensions 1 wordt opgeteld.

In [26]:
df['EXTENSION'] = df['EXTENSION'] + 1

df.head()

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE,FULL_NAME
0,4,Denis,Pagé,Branch Manager,+33 1 68 94 52 20,326.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6,Denis Pagé
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,337.0,+33 1 68 94 56 60,EMichel@grtd123.com,1995-06-08,6,Élizabeth Michel
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,379.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6,Émile Clermont
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,399.0,+33 1 68 94 56 60,EJauvin@grtd123.com,1997-08-16,6,Étienne Jauvin
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1819.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13,Elsbeth Wiesinger

Elke 'Branch Manager' wordt nu 'General Manager'. Schrijf code zodat deze wijziging doorgevoerd wordt in het DataFrame.

In [27]:
df['POSITION_EN'] = df['POSITION_EN'].replace('Branch Manager', 'General Manager')

df.head()

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE,FULL_NAME
0,4,Denis,Pagé,General Manager,+33 1 68 94 52 20,326.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6,Denis Pagé
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,337.0,+33 1 68 94 56 60,EMichel@grtd123.com,1995-06-08,6,Élizabeth Michel
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,379.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6,Émile Clermont
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,399.0,+33 1 68 94 56 60,EJauvin@grtd123.com,1997-08-16,6,Étienne Jauvin
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1819.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13,Elsbeth Wiesinger

### Kolommen

Verander de kolomnaam 'POSITION_EN' naar 'POSITION'.

In [28]:
df = df.rename(columns={'POSITION_EN': 'POSITION'})

df.head()

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE,FULL_NAME
0,4,Denis,Pagé,General Manager,+33 1 68 94 52 20,326.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6,Denis Pagé
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,337.0,+33 1 68 94 56 60,EMichel@grtd123.com,1995-06-08,6,Élizabeth Michel
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,379.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6,Émile Clermont
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,399.0,+33 1 68 94 56 60,EJauvin@grtd123.com,1997-08-16,6,Étienne Jauvin
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1819.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13,Elsbeth Wiesinger

## Data verwijderen

### Rijen

De medewerkers op indexen 98, 99 en 100 hebben helaas ontslag genomen.<br>
Verwijder de bijbehorende rijen uit het DataFrame. Gebruik slechts één keer de .drop()-methode.

In [29]:
df = df.drop([98, 99, 100])

df.tail()

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE,FULL_NAME
95,118,Gianni,Vertemati,Level 1 Sales Representative,+(41) 17 12 13 14,1255.0,+(41) 17 12 13 20,GVertemati@grtd123.com,2000-02-10,37,Gianni Vertemati
96,119,Gracy,Gellens,General Manager,+32 16 20.73.21,1350.0,+32 16 20.73.32,GGellens@grtd123.com,1999-09-10,38,Gracy Gellens
97,120,Giele,Laermans,Level 1 Sales Representative,+32 16 20.73.21,1341.0,+32 16 20.73.32,GLaermans@grtd123.com,1999-11-15,38,Giele Laermans
101,124,Sabine,Grüner,Level 3 Sales Representative,+(43) 13 79 56 32,349.0,+(43) 13 79 56 33,SGruner@grtd123.com,1998-02-18,39,Sabine Grüner
102,999,Sofia,Test,Sales Representative,+31 000000000,1.0,None,sofia@test.com,2024-01-01,1,Sofia Test

### Kolommen

Faxen zijn inmiddels ouderwets: niemand gebruikt zijn/haar faxnummer nog.<br>
Verwijder de bijbehorende kolom uit het DataFrame.

In [30]:
df = df.drop(columns=['FAX'])

df.head()

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION,WORK_PHONE,EXTENSION,EMAIL,DATE_HIRED,SALES_BRANCH_CODE,FULL_NAME
0,4,Denis,Pagé,General Manager,+33 1 68 94 52 20,326.0,DPage@grtd123.com,1996-11-03,6,Denis Pagé
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,337.0,EMichel@grtd123.com,1995-06-08,6,Élizabeth Michel
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,379.0,EClermont@grtd123.com,1998-04-07,6,Émile Clermont
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,399.0,EJauvin@grtd123.com,1997-08-16,6,Étienne Jauvin
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1819.0,EWiesinger@grtd123.com,1997-02-27,13,Elsbeth Wiesinger